### ISSUE TITLE
[FIX] Pre-existing algorithms do not fit the contribution guidelines

### ISSUE THREAD

**Issue by realstealthninja** [TheAlgorithms/C-Plus-Plus#2456]
### Detailed description

<h1 align="center">Times change </h1>  
<p align="center">so does the development of algorithms and documentation</p>

Some of the older algorithms existing in this repository do not fit the [contribution guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md).

A short list of examples:
 - [Armstrong number](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/armstrong_number.cpp)
 - [binary exponent](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/binary_exponent.cpp)
 - [check prime](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/check_prime.cpp) 
 - [complex numbers](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/complex_numbers.cpp)
 - [square root double](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/math/sqrt_double.cpp)

### Context

Educating new developers on coding standards is a major priority; As the industry today relies heavily on documentation;
If you were to ask any API developer/user on what the most important part of their development and use it will always be:
 - Code quality
 - documentation

having a fast and performant algorithm is good but whats the point if you cant understand how it works or even why it works.

I think it is in the best interest of us to document our algorithms.

As i consider all algorithms must be:
- beautiful
- understandable
- educational

### Additional information

Others in the past have made major changes like this to this repository and i think its time for us to do the same. to keep the torch moving.

An homage to [@kvedala] for their part in trying to standardize this repository #805

**Comment by Kunal766** [comment]
Hi,  I wanted to start contributing to this repository ,can you assign me this problem

**Comment by realstealthninja** [comment]
No sorry no assigning in this repository just start making a pull request and we will review to help you.❤️

Note: assigning requires triage access

**Comment by CodeSinghh** [comment]
how can help so that this issue will be resolved

**Comment by realstealthninja** [comment]
> how can help so that this issue will be resolved
just find an algorithm that does not fit the contribution guidelines and start fixing it! we will close this issue once *ALL* the algorithms are fixed! :smile:

**Comment by ewd00010** [comment]
# Math Directory Checklist
### (pending update)
Below is the list of algorithms to be checked within the maths repository.
- [X] aliquot_sum.cpp
- [] approximate_pi.cpp  [^1]
- [] area.cpp [^2]
- [X] armstrong_number.cpp
- [X] binary_exponent.cpp
- [X] binomial_calculate.cpp
- [X] check_amicable_pair.cpp
- [X] check_factorial.cpp
- [X] check_prime.cpp
- [] complex_numbers.cpp [^2]
- [] double_factorial.cpp
- [] eratosthenes.cpp
- [] eulers_totient_function.cpp
- [] extended_euclid_algorithm.cpp
- [] factorial.cpp
- [] fast_power.cpp
- [] fibonacci.cpp
- [] fibonacci_fast.cpp
- [] fibonacci_large.cpp
- [] fibonacci_matrix_exponentiation.cpp
- [] fibonacci_sum.cpp
- [] finding_number_of_digits_in_a_number.cpp
- [] gcd_iterative_euclidean.cpp
- [] gcd_of_n_numbers.cpp
- [] gcd_recursive_euclidean.cpp
- [] integral_approximation.cpp
- [] integral_approximation2.cpp
- [] inv_sqrt.cpp
- [] large_factorial.cpp
- [] large_number.h
- [] largest_power.cpp
- [] lcm_sum.cpp
- [] least_common_multiple.cpp
- [] linear_recurrence_matrix.cpp
- [] magic_number.cpp
- [] miller_rabin.cpp
- [] modular_division.cpp
- [] modular_exponentiation.cpp
- [] modular_inverse_fermat_little_theorem.cpp
- [] modular_inverse_simple.cpp
- [] n_bonacci.cpp
- [] n_choose_r.cpp
- [] ncr_modulo_p.cpp
- [] number_of_positive_divisors.cpp
- [] perimeter.cpp
- [] power_for_huge_numbers.cpp
- [] power_of_two.cpp
- [] prime_factorization.cpp
- [] prime_numbers.cpp
- [] primes_up_to_billion.cpp
- [] quadratic_equations_complex_numbers.cpp
- [] realtime_stats.cpp
- [] sieve_of_eratosthenes.cpp
- [] sqrt_double.cpp
- [] string_fibonacci.cpp
- [] sum_of_binomial_coefficient.cpp
- [] sum_of_digits.cpp
- [] vector_cross_product.cpp
- [] volume.cpp

[^1]: This algorithm needs a small amount of changes
[^2]: This algorithm needs a large amount of changes

**Comment by rbevin777** [comment]
In terms of making these changes/fixes to the style to fit the guidelines. How do you want PRs to work? My thinking was just 1 small PR based on changes to one module to minimize the changes which need reviewed.

**Comment by realstealthninja** [comment]
> In terms of making these changes/fixes to the style to fit the guidelines. How do you want PRs to work? My thinking was just 1 small PR based on changes to one module to minimize the changes which need reviewed.

one pr for one file

**Comment by rbevin777** [comment]
I'm starting to look at the `area.cpp` file [here](https://github.com/rbevin777/C-Plus-Plus/tree/Fix-pre-existing-algorithm-area.cpp-to-follow-guidelines) just so no one picks it up by accident 😁

**Comment by Bl1xvan** [comment]
Please assign me fast_power.cpp

**Comment by dylancusson** [comment]
Submitted a PR for sum_of_digits.cpp
It's my first PR so let me know if adjustments are needed.
I did forget my .vscode json was in there, I'll remember to exclude it from my commit next time!

**Comment by realstealthninja** [comment]
# let's get this finished

We still need more help on this!
Open a pe for any of the algorithms in the math directory and fix it by adding documentation and tests!

Please mention it here by referencing the pr with the # prefix ♥️

**Comment by realstealthninja** [comment]
if anyone's interested in doing an algorithm in this list for hacktoberfest feel free to raise an issue of your preferred algorithm. Ill be happy to apply the label to it. :heart:  happy hacking!

**Comment by ritk20** [comment]
> * [ ]  lcm_sum.cpp [1](#user-content-fn-1-cab624de0d6cd79d36c1dd939d79fdc3) [4](#user-content-fn-3-cab624de0d6cd79d36c1dd939d79fdc3)[2](#user-content-fn-4-cab624de0d6cd79d36c1dd939d79fdc3) _is there a more efficient version of this?_

I don't think there is a more efficient version. I found some proofs of this algorithm [here](https://math.stackexchange.com/questions/761670/how-to-find-this-lcm-sum-function-textlcm1-n-textlcm2-n-cdots-t) and [here](https://codeforces.com/blog/entry/14073) but I couldn't find anything better. 

If there isn't a better approach, I will fix the doc & test issues.

**Comment by Rohith68320** [comment]
Hello, I'd like to start contributing to this issue.
For my first contribution, I would like to update and refactor the file : `binary_exponentiation.cpp`

After this file is completed and merged, I would also be happy to continue working on additional math-related algorithms.

Please let me know if `binary_exponentiation.cpp` is available to work on.

**Comment by sudheerxdev** [comment]
---

## **Issue #2456 - Pre-existing algorithms not meeting guidelines**

```markdown
## Review Feedback

### Current Status Analysis
Many existing algorithms don't follow the repo's contribution guidelines regarding:
- Comments and documentation standards
- Naming conventions
- File structure and organization

### Refinement Strategy

#### Phase 1: Audit (High Priority)
- Scan existing algorithms for guideline violations
- Create checklist of required fixes
- Prioritize high-impact files

#### Phase 2: Documentation
- Add doxygen comments to functions
- Include complexity analysis (Time/Space)
- Add example usage for each algorithm

#### Phase 3: Code Quality
- Rename variables to be descriptive (no single letters except loop counters)
- Remove magic numbers (use `const` instead)
- Ensure consistent formatting

### Specific Guidelines to Enforce:

**Comment by 13-Prabhat** [comment]
Hi! I'd like to contribute to this. I'll start with armstrong_number.cpp — add Doxygen-style file and function documentation, in-file assert-based self-tests, and bring it up to the current contribution guidelines. Incremental PR for one file at a time. Can I get assigned?
